config/routes.rb
Rails.application.routes.draw do
  
  root to: 'words#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resource :relationships, only: [:create, :destroy]
    member do
      get :likes
      get :followings
      get :followers
    end
  end

  resources :words do
    resource :likes, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
  
    validates :name, presence: true
    validates :email, presence: true, uniqueness: true

    has_one_attached :image
    has_many :words, :dependent => :destroy
    has_many :likes, :dependent => :destroy
    has_many :relationships, :dependent => :destroy
    has_many :followings, through: :relationships, source: :follow
    has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
    has_many :followers, through: :reverse_of_relationships, source: :user
    
    paginates_per 10

    def follow(other_user)
      unless self == other_user
        self.relationships.find_or_create_by(follow_id: other_user.id)
      end
    end
  
    # def unfollow(other_user)
    #   relationship = self.relationships.find_by(follow_id: other_user.id)
    #   relationship.destroy if relationship
    # end
  
    def following?(other_user)
      self.followings.include?(other_user)
    end

    def count_words
      self.words.count
    end

    def count_followers
      self.followers.count
    end

    def count_followings
      self.followings.count
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :likes, :followings, :followers]
  skip_before_action :login_required, only: [:new, :create, :show, :likes, :followings, :followers]

  def index
    @users = User.all
  end

  def show
    @q = Word.where(user_id: @user.id).ransack(params[:q])
    @words = @q.result(distinct: true).page(params[:page])
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to login_path, notice: "ユーザ「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "ユーザ「#{@user.name}」を更新しました。"
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: "ユーザ「#{@user.name}」を削除しました。"
  end

  def likes
    @q = Like.where(user_id: @user.id).ransack(params[:q])
    @likes = @q.result(distinct: true).page(params[:page])
  end

  def followings
    @q = @user.followings.ransack(params[:q])
    @followings = @q.result(distinct: true).page(params[:page])
  end

  def followers
    @q = @user.followers.ransack(params[:q])
    @followers = @q.result(distinct: true).page(params[:page])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :image, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.slim
.main.users-_form
  .container
    .form.users-form
      .form-body
        .form-error
          - if user.errors.present?
            ul#error_explanation
              - user.errors.full_messages.each do |message|
                li= message
        = form_with model: @user, local: true do |f|
          .form-group
            = f.label :name, '名前'
            = f.text_field :name, class: 'form-control'
          .form-group
            = f.label :email, 'メールアドレス'
            = f.text_field :email, class: 'form-control'
          .form-group
            = f.label :image
            = f.file_field :image, class: 'form-control'
          .form-group
            = f.label :password, 'パスワード'
            = f.password_field :password, class: 'form-control'
          .form-group
            = f.label :password_confirmation, 'パスワード(確認)'
            = f.password_field :password_confirmation, class: 'form-control'
          = f.submit '登録する', class: 'btn btn-primary'

app/views/users/_show.html.slim
.user
    = image_tag @user.image, :size =>'50x50' if @user.image.attached?
    h2 
    = @user.name
    p 
    = "email: #{@user.email}"

- if current_user && current_user.id == @user.id
    = link_to '編集', edit_user_path, class: 'btn btn-primary'
- if current_user && current_user.id != @user.id
    - if current_user.following?(@user)
        = link_to 'フォロー解除', user_relationships_path(@user.id, :show_user_id => @user.id), method: :delete, class: 'btn btn-primary'
    - else   
        = link_to 'フォロー', user_relationships_path(@user.id, :show_user_id => @user.id), method: :post, class: 'btn btn-primary'

app/views/users/edit.html.slim
h1 ユーザの編集

.nav.justify-content-end
  = link_to '一覧', users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user }

app/views/users/followers.html.slim
.main.users-show
  .container
    = render partial: 'show', locals: { user: @user }
    ul.user-tabs
      li
        = link_to "投稿 #{@user.count_words}", @user
      li
        = link_to 'いいね！', likes_user_path
      li
        = link_to "フォロー中 #{@user.count_followings}", followings_user_path
      li.active
        = link_to "フォロワー #{@user.count_followers}", followers_user_path
      
    - @followers.each do |user|
      .words-index-item
        .word-left
          = link_to user
            = image_tag user.image, :size =>'50x50' if user.image.attached?
        .word-right
          span.mgr-20
            = user.name
            - if current_user && current_user.id != user.id
                - if current_user.following?(user)
                    = link_to 'フォロー解除', user_relationships_path(user.id, :show_user_id => @user.id), method: :delete, id: "フォロー解除#{user.id}", class: 'btn btn-primary mx-4'
                - else   
                    = link_to 'フォロー', user_relationships_path(user.id, :show_user_id => @user.id), method: :post, id: "フォロー#{user.id}", class: 'btn btn-primary mx-4'
    ul
      = paginate @followers

app/views/users/followings.html.slim
.main.users-show
  .container
    = render partial: 'show', locals: { user: @user }
    ul.user-tabs
      li
        = link_to "投稿 #{@user.count_words}", @user
      li
        = link_to 'いいね！', likes_user_path
      li.active
        = link_to "フォロー中 #{@user.count_followings}", followings_user_path
      li
        = link_to "フォロワー #{@user.count_followers}", followers_user_path
      
    - @followings.each do |user|
      .words-index-item
        .word-left
          = link_to user
            = image_tag user.image, :size =>'50x50' if user.image.attached?
        .word-right    
          span.mgr-20
            = user.name
            - if current_user && current_user.id != user.id
                - if current_user.following?(user)
                    = link_to 'フォロー解除', user_relationships_path(user.id, :show_user_id => @user.id), method: :delete, id: "フォロー解除#{user.id}", class: 'btn btn-primary mx-4'
                - else   
                    = link_to 'フォロー', user_relationships_path(user.id, :show_user_id => @user.id), method: :post, id: "フォロー#{user.id}", class: 'btn btn-primary mx-4'
    ul
      = paginate @followings

app/views/users/index.html.slim
h1 ユーザ一覧

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= User.human_attribute_name(:name)
      th= User.human_attribute_name(:created_at)
      th
  tbody
    - @users.each do |user|
      tr
        td= link_to user.name, user
        td= user.created_at
        td
          = link_to '編集', edit_user_path(user), class: 'btn btn-primary mr-3'
          = link_to '削除', user, method: :delete, data: { confirm: "タスク「#{user.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/users/likes.html.slim
.main.users-show
  .container
    = render partial: 'show', locals: { user: @user }
    ul.user-tabs
      li
        = link_to "投稿 #{@user.count_words}", @user
      li.active
        = link_to 'いいね！', likes_user_path
      li
        = link_to "フォロー中 #{@user.count_followings}", followings_user_path
      li
        = link_to "フォロワー #{@user.count_followers}", followers_user_path

    - @likes.each do |like|
        - word = Word.find_by(id: like.word_id)
        .words-index-item
          .word-left
            = link_to word.user
              = image_tag word.user.image, :size =>'50x50' if word.user.image.attached?
          = link_to word do
            .word-right
              span.mgr-20
                = word.name
              span.mgr-10
                | by &nbsp;
                = word.user.name
              | いいね &nbsp;
              = Like.where(word_id: word.id).count
    ul
      = paginate @likes

app/views/users/new.html.slim
h1 ユーザの新規登録

.nav.justify-content-end
  = link_to '一覧', users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user }

app/views/users/show.html.slim
.main.users-show
  .container
    = render partial: 'show', locals: { user: @user }
    ul.user-tabs
      li.active
        = link_to "投稿 #{@user.count_words}", @user
      li
        = link_to 'いいね！', likes_user_path
      li
        = link_to "フォロー中 #{@user.count_followings}", followings_user_path
      li
        = link_to "フォロワー #{@user.count_followers}", followers_user_path
      
    - @words.each do |word|
      .words-index-item
        .word-left
          = link_to word.user
            = image_tag word.user.image, :size =>'50x50' if word.user.image.attached?
        = link_to word do
          .word-right
            span.mgr-20
              = word.name
            span.mgr-10
              | by &nbsp;
              = word.user.name
            | いいね &nbsp;
            = Like.where(word_id: word.id).count
    ul
      = paginate @words