config/routes.rb
Rails.application.routes.draw do
  
  root to: 'words#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resource :relationships, only: [:create, :destroy]
    member do
      get :likes
      get :followings
      get :followers
    end
  end

  resources :words do
    resource :likes, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/word.rb
class Word < ApplicationRecord
    validates :name, presence: true, length: { maximum: 30 }
    validates :description, presence: true
    validate :validate_name_not_including_comma
  
    belongs_to :user
    has_many :likes, :dependent => :destroy

    scope :recent, -> { order(created_at: :desc) }
  
    paginates_per 10

    def user
      if self.user_id
        User.find(self.user_id)
      end
    end

    def self.ransackable_attributes(auth_object = nil)
      %w[name created_at]
    end

    def self.ransackable_associations(auth_object = nil)
      %[]
    end

    private
  
    def validate_name_not_including_comma
      errors.add(:name, 'にカンマを含めることはできません') if name&.include?(',')
    end


end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:edit, :update, :destroy]
  skip_before_action :login_required, only: [:index, :show]

  def index
    # @words = current_user.words.recent
    # @words = current_user.words <==>  Word.where(user_id: current_user.id)
    @q = Word.all.ransack(params[:q])
    @words = @q.result(distinct: true).page(params[:page])
  end

  def show
    @word = Word.find(params[:id])
  end

  def top
  end

  def new
    @word = Word.new
  end

  def edit
  end

  def create
    @word = current_user.words.new(word_params)

    if @word.save
      redirect_to @word, notice: "投稿「#{@word.name}」を登録しました。"
    else
      render :new
    end
  end

  def update
    if @word.update(word_params)
      redirect_to words_url, notice: "投稿「#{@word.name}」を更新しました。"
    else
      render :new
    end
  end

  def destroy
    @word.destroy
    redirect_to words_url, notice: "投稿「#{@word.name}」を削除しました。"
  end

  private

  def word_params
    params.require(:word).permit(:name, :description)
  end

  def set_word
    @word = current_user.words.find(params[:id])
  end
end

app/helpers/words_helper.rb
module WordsHelper
    # require "redcarpet"
    # require "coderay"

    # class HTMLwithCoderay < Redcarpet::Render::HTML
    #     def block_code(code, language)
    #         language = language.split(':')[0]

    #         case language.to_s
    #         when 'rb'
    #             lang = 'ruby'
    #         when 'yml'
    #             lang = 'yaml'
    #         when 'css'
    #             lang = 'css'
    #         when 'html'
    #             lang = 'html'
    #         when ''
    #             lang = 'md'
    #         else
    #             lang = language
    #         end

    #         CodeRay.scan(code, lang).div
    #     end
    # end

    # def markdown(text)
    #     html_render = HTMLwithCoderay.new(filter_html: true, hard_wrap: true)
    #     options = {
    #         autolink: true,
    #         space_after_headers: true,
    #         no_intra_emphasis: true,
    #         fenced_code_blocks: true,
    #         tables: true,
    #         hard_wrap: true,
    #         xhtml: true,
    #         lax_html_blocks: true,
    #         strikethrough: true
    #     }
    #     markdown = Redcarpet::Markdown.new(html_render, options)
    #     markdown.render(text)
    # end
end

app/views/words/_form.html.slim
.main.words-show
  .container.mt-5
    .word-form.p-5
      .form-error
        - if @word.errors.present?
          ul#error_explanation
            - @word.errors.full_messages.each do |message|
              li= message
      = form_with model: @word, local: true do |f|
        .form-group
          = f.label :name
          = f.text_field :name, class: 'form-control', id: 'word_name'
        .form-group
          = f.label :description
          = f.text_area :description, rows: 20, class: 'form-control', id: 'word_description'
        = f.submit '登録する', class: 'btn btn-primary'

app/views/words/edit.html.slim
h1 タスクの編集

.nav.justify-content-end
  = link_to '一覧', words_path, class: 'nav-link'

= render partial: 'form', locals: { word: @word }

app/views/words/index.html.slim
.main.words-index
  .container
    .form-body
      = search_form_for @q, class: 'mb-1' do |f|
        / .form-group.row
        /   .col-sm-9  
        /     = f.search_field :name_cont, class: 'form-control', type: 'search', placeholder: "キーワードを入力"
        /   .col-sm-3
        /     = f.submit class: 'btn btn-primary'
        .form-group
            = f.search_field :name_cont, class: 'form-control', type: 'search', placeholder: "キーワードを入力"
            = f.submit class: 'btn btn-primary'
    .page_entry
      = page_entries_info @words
    - @words.each do |word|
        .words-index-item
          .word-left
            = link_to word.user
              = image_tag word.user.image, :size =>'50x50' if word.user.image.attached?
          = link_to word do
            .word-right
              span.mgr-20
                = word.name
              span.mgr-10
                | by &nbsp;
                = word.user.name
              | いいね &nbsp;
              = Like.where(word_id: word.id).count
          .text-right
            p
              |🕒
              = word.created_at.strftime('%Y/%m/%d')
    ul
      = paginate @words

/ = link_to '新規登録', new_word_path, class: 'btn btn-primary'
  
/ thead.thead-default
/   tr
/     th= sort_link(@q, :name)
/     / th= Word.human_attribute_name(:name)
/     th= sort_link(@q, :created_at)
/     / th= Word.human_attribute_name(:created_at)
/     th= 'いいね'
/         / td
/         /   = link_to '編集', edit_word_path(word), class: 'btn btn-primary mr-3'
/         /   = link_to '削除', word, method: :delete, data: { confirm: "タスク「#{word.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/words/new.html.slim
= render partial: 'form', locals: { word: @word }

app/views/words/show.html.slim
.main.words-show
  .container.mt-5
    h1.mx-3
      = @word.name
    ul.list-inline
      li.list-inline-item.mx-3
        = link_to @word.user
          = image_tag @word.user.image, :size =>'50x50' if @word.user.image.attached?
      li.list-inline-item.mx-2
        = @word.user.name
      - if current_user && current_user.id == @word.user_id
        li.list-inline-item.mx-3
          = link_to '編集', edit_word_path, class: 'btn btn-primary mr-3'
        li.list-inline-item
          = link_to '削除', @word, method: :delete, data: { confirm: "ワード「#{@word.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'
      li.list-inline-item.mx-3
        = "いいね！ #{Like.where(word_id: @word.id).count}"
      li.list-inline-item.mx-3
        = "最終更新日 #{@word.updated_at.strftime('%Y/%m/%d')}"

    .word-form.p-5
      / = simple_format(h(markdown(@word.description)), {}, sanitize: false, wrapper_tag: "div")
      = markdown(@word.description)
      .mt-5
        - if current_user
          - unless current_user.id == @word.user.id
            - if Like.where(word_id: @word.id).count > 0
              = link_to word_likes_path(@word.id), method: :delete, id: 'いいね解除' do
                p style="display: inline-block; font-size: 20px;"
                  | &#x2764;
              | いいね済
            - else
              = link_to word_likes_path(@word.id), method: :post, id: 'いいね' do
                p style="display: inline-block; font-size: 25px;"
                  | &#x2661;
              | いいね！

app/views/words/top.html.slim
h1 トップ画面